/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "magicRestAPI",
            "endpoint": "https://znoy1b2w05.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://6jko7wu5i5ei5p442o2k2f2amm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3bwysvtz5zf2tcp7gcd7mrkqie",
    "aws_cognito_identity_pool_id": "us-east-1:8147e93f-a402-478e-bebb-2ca11cf82ab1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GL2udjqVj",
    "aws_user_pools_web_client_id": "5o853106il9vtlkk3u6n3r54h1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "wager-profiles195802-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
